name: Daily Skate Deals Scrape 2

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb firefox-esr geckodriver

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager fake-useragent

      - name: Run scraper
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3  # give Xvfb time to initialize
          python sales_scraper2.py

      - name: Check if HTML was generated
        run: |
          if [ -f "sale_items_chart.html" ]; then
            echo "ARTIFACT_EXISTS=true" >> $GITHUB_ENV
          else
            echo "ARTIFACT_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Upload HTML if created
        if: env.ARTIFACT_EXISTS == 'true'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: sale-chart
          path: sale_items_chart.html
