name: Daily Scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium webdriver-manager fake-useragent

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Get the installed Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        # Fetch the Chromedriver version compatible with the installed Chrome version
        CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "Falling back to latest Chromedriver version"
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        fi
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        rm chromedriver_linux64.zip
        # Verify Chrome and Chromedriver versions
        google-chrome --version
        chromedriver --version

    - name: Run scraper
      run: python zumiez_analyzer-grok3.py
      env:
        CI: true

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add sale_items_chart.html previous_data.json *_debug_*.html
        git commit -m "Update sale_items_chart.html with latest scrape data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}