name: Daily Scrape Job

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Match Python 3.9.22

      # Install Firefox and dependencies
      - name: Install Firefox and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox xvfb libx11-xcb1 libdbus-glib-1-2 libxt6 libgtk-3-0 libasound2
          firefox --version

      # Install geckodriver manually
      - name: Install geckodriver
        run: |
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          geckodriver --version

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium==4.17.2 webdriver-manager fake-useragent

      # Run the scraper with Xvfb
      - name: Run scraper
        run: |
          Xvfb :99 -screen 0 1920x1080x24 -ac -noreset &
          export DISPLAY=:99
          python sales_scraper2.py
        env:
          PYTHONUNBUFFERED: 1
          GECKODRIVER_LOG_LEVEL: debug

      # Upload artifacts
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-output
          path: |
            *.html
            *.json
            geckodriver.log